### ISSUE TITLE
Exercise submission requires equals assignment operator

### ISSUE THREAD

**Issue by joevus** [UjjayiniDas/BSOS_DataCuration_R_Tutorial#1]
@UjjayiniDas 
First off, this was really cool that you can have in-place exercises.

One thing I noticed. The exercise to impute missing values requires the user to use `=` as an assignment operator rather than `<-`. I think ideally it should except either one. When I replaced the operator with `=` it worked. See screenshot below.

Might be a learnr thing?

![Screen Shot 2022-11-15 at 5 25 46 PM](https://user-images.githubusercontent.com/13547828/202038440-439a0585-0c21-4157-aceb-1ed0bdc2a78d.png)

**Comment by UjjayiniDas** [comment]
Yeah, thanks for pointing that out! As far as I remember I had to use "="
because that's how 'gradethis' was working. I will double check if that can
be made more flexible with "<-".
Thank you,
Ujjayini

*______________________________________________________*

*______________________*

*Ujjayini Das | Pre-Doctoral Fellow*
(she/her/hers)

University of Maryland, College Park | Joint Program in Survey Methodology
and Data Science (JPSM)
1218G Lefrak Hall, 7251 Preinkert Drive, College Park, MD 20742
Telephone: 301-314-9833
Email: ***@***.***

**Comment by joevus** [comment]
Sounds good. Understood if it's a gradethis thing might need to stay.

**Comment by UjjayiniDas** [comment]
The thing is that I had to provide the correct solution code for this
exercise which will be compared with what the student is writing. So, I
didn't have an option to provide both of the syntax which I should have
ideally. Maybe we can think about putting the checking method in a
different way so that it doesn't depend on the   operator. I will look into
it more!
Thank you,
Ujjayini

*______________________________________________________*

*______________________*

*Ujjayini Das | Pre-Doctoral Fellow*
(she/her/hers)

University of Maryland, College Park | Joint Program in Survey Methodology
and Data Science (JPSM)
1218G Lefrak Hall, 7251 Preinkert Drive, College Park, MD 20742
Telephone: 301-314-9833
Email: ***@***.***
